# Generated by Django 2.2.1 on 2019-05-19 22:48

from django.db import migrations, models
import evento.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=evento.utils.now_plus_5_minutes),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.IntegerField(),
        ),
    ]
